### ISSUE TITLE
Tutorial typos

### ISSUE THREAD

**Issue by EdwinVanRooij** [juanchosaravia/Keddit#4]
Hello and thank you for writing an amazing tutorial on Kotlin for Android. To improve the tutorial even further, I've manually created a list of some little spelling errors I've found on the website of the tutorial. I hope you'll use it for the best. 
https://medium.com/@juanchosaravia/learn-kotlin-while-developing-an-android-app-introduction-567e21ff9664#.wcgi0xk9j I've found the next grammar/English typing errors:

First I will say the original text, then the correct way of saying it.
Example: "this is the original tekst" --> "this is the original **text**"

- Introduction
"If you have any question" --> "If you have any **questions**"
Forgot the dot after "otherwise we will learn together :)"
- Part 1
"use Kotlin and left everything" --> "use Kotlin and **leave** everything"
"that it’s already complete" --> "that **is** already complete"
- Part 2
The word "this" is used before singular things, while "these" is used before multiple things. 
Example: "this book is beautiful" and "these books are beautiful". I've seen this mistake a couple of times, hope you learn from it like I've learned Kotlin from the tutorial :).
"some of this objects to primitive types internally." --> "some of **these** objects to primitive types internally."
"about this concepts, checkout" --> "about **these** concepts, checkout"
- Part 3
"as we will be" --> "**As** we will be"
"Also we are going to understand how does it works" --> "Also we are going to understand **how it works**"
"awesome trick!" --> "**Awesome** trick!"
"first Extention Fucntion" --> "first **Extension Function**"
"interoperability you can find it here." --> "interoperability can be found here."
"Here you can see the commit of all this changes:" --> "Here you can see the commit of all **these** changes:"
"...er! but wait! W..." --> "...er! **But** wait! W..."
"This interface allow us to have a generic list of" --> "This interface **allows** us to have a generic list of"
- Part 4
In English, you only use _an_ when the word after it is **pronounced** with a vowel first, for example: a book, a horse, an eye, an ear.
" type to an String with" --> " type to **a** String with"
" this example is perfect :)" --> " this example **it's** perfect :)**.**"
" but Kotlin make it great to allows you to exclude" --> " but Kotlin makes it great, because it allows you to exclude"

I'm now tired of watching these ones. I hope this is helpful for you!

**Comment by juanchosaravia** [comment]
@EdwinvRooij you rock!! thanks man! I really appreciate it. 
For sure I'll update it and this is really useful for me also to continue learning english 😃

**Comment by EdwinVanRooij** [comment]
@juanchosaravia you're welcome and thank you for the tutorial. :)
I'm still working on improving my own app now by following your steps. :smile:

**Comment by juanchosaravia** [comment]
Everything updated as now that Kotlin is official more people is reading the article 😃 
Thanks man!! Really appreciated!
